[package]
name = "wemux-login"
version = "0.1.0"
authors = ["Bernd Busse <bernd AT busse-net DOT de>"]

[dependencies]
docopt = "0.8"
serde = "1.0"
serde_derive = "1.0"
regex = "0.2"
lazy_static = "1.0"
